chance page title
samueljrz/NLW-IV-MoveIt pull request #2
Opened 2021-02-23 14:57 UTC by samueljrz

2021-02-23 16:43 UTC, kelyAna approved these changes

2021-02-23 17:35 UTC, ivensgustavo approved these changes

2021-02-23 18:30 UTC, kelyAna approved these changes

2021-02-23 18:56 UTC, ivensgustavo approved these changes

2021-02-23 19:32 UTC, GuilhermRodrigues approved these changes

2021-02-24 12:11 UTC, kelyAna approved these changes

2021-02-24 12:58 UTC, AlysonBasilio commented on moveit-next/src/components/CountDown.tsx
> +      setText('Pausar o ciclo')
Acho interessante jogar todos os textos possíveis que vc utilizou no setText em um enum. Por exemplo:
```ts
enum countdownButtonLabels {
  pause: 'Pausar o ciclo',
  start: 'Iniciar um ciclo'
}
```

Isso concentrará todos os textos possíveis em um lugar só, facilitando a manutenção e evita a mistura de palavras em inglês do código com palavras em português do front

2021-02-24 13:01 UTC, AlysonBasilio requested changes
Acho que dá pra dar uma melhorada no componente Countdown

2021-02-24 13:38 UTC, kelyAna approved these changes

2021-02-24 13:40 UTC, merged